Python : getting started sample
Azure-Samples/MqttApplicationSamples pull request #45
Opened 2023-05-31 17:33 UTC by olivakar

## Purpose
The first sample for python.

Some of the Paho Client Wrapper code is still unused. Hopefully as we write other samples I will have a better idea what functions are gonna be used.

Some codes are still commented 
9like the certificates path) as the more complex samples need to be tested against that code path. Did not want to uncomment as I am not 100 percent sure.

## Checklist
- [ ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `main` branch. 
  - [ ] I have merged the latest `main` branch prior to submission and re-merged as needed after I took any feedback.
  - [ ] I will squashed my changes into one with a clear description of the change when I complete the PR.

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  ...

## What to Check
Verify that the following are valid
* ...

## Other Information

2023-05-31 19:55 UTC, vishnureddy17 commented
I think this sample also needs to subscribe to the `sample/+` topic to align with the [dotnet sample](https://github.com/Azure-Samples/MqttApplicationSamples/blob/4a9ba04c8fc91dafe89dd6f5b06bd0ae56c185f4/scenarios/getting_started/dotnet/getting_started/Program.cs#LL19C47-L19C55).

2023-06-06 15:07 UTC, cartertinney approved these changes

2023-06-06 15:07 UTC, cartertinney commented on mqttclients/python/pahoclientwrapper/paho_client_wrapper.py
> +        granted_qos_list = list(granted_qos)
I'm guessing this is an MQTT5 thing I don't fully understand? Why are there (potentially) multiple QoS values?

2023-06-06 15:39 UTC, rido-min requested changes
The sample fails if the .env file does not have `MQTT_KEY_FILE_PASSWORD`

```
  File "/home/codespace/.python/current/lib/python3.10/site-packages/pahoclientwrapper/paho_client_wrapper.py", line 65, in __init__
    password=connection_settings['MQTT_KEY_FILE_PASSWORD']
KeyError: 'MQTT_KEY_FILE_PASSWORD'
```

2023-06-06 18:48 UTC, olivakar commented on mqttclients/python/pahoclientwrapper/mqtt_helpers.py
> +class IncomingAckList(Generic[T]):
discussion needed

2023-06-06 22:59 UTC, olivakar commented on mqttclients/python/pahoclientwrapper/connection_settings.py
> +    final_values = {**default_values, **envvar_values, **envfile_values}
order of precedence is envfile, envvar, and default

2023-06-07 23:43 UTC, closed without merging