Environment variable bugs and other .NET best practices
Azure-Samples/MqttApplicationSamples pull request #54
Opened 2023-06-15 16:49 UTC by patilsnr

2023-06-15 16:57 UTC, vaavva approved these changes
Please get a C# dev sign-off as well, but looks good to me!

2023-06-15 16:57 UTC, vaavva commented on mqttclients/dotnet/MQTTnet.Client.Extensions/MqttConnectionSettings.cs
> +        throw new ArgumentException($"An environment variable's type was specified incorrectly: {envVarName}={envVarValue}");
Can you include that it should be an int (and bool in the one below) in the error message, since we know what it should be?

2023-06-15 17:35 UTC, timtay-microsoft approved these changes

2023-06-15 17:44 UTC, rido-min requested changes
add unit tests to validate the new behavior for invalid values

2023-06-15 18:34 UTC, patilsnr commented on mqttclients/dotnet/MQTTnet.Client.Extensions/CommandProducer.cs
> +                MqttClientPublishResult pubAck = await mqttClient.PublishAsync(new MqttApplicationMessageBuilder()
What kind of check do you have in mind?

2023-06-15 18:54 UTC, rido-min commented on mqttclients/dotnet/MQTTnet.Client.Extensions/CommandProducer.cs
> +                MqttClientPublishResult pubAck = await mqttClient.PublishAsync(new MqttApplicationMessageBuilder()
check if it was a successful ack, if not, we should return an error to the command server (aka producer) to let the server the client did not get a response. 

@drwill-ms might have more insights.

2023-06-15 20:31 UTC, drwill-ms commented on mqttclients/dotnet/MQTTnet.Client.Extensions/CommandProducer.cs
> +                MqttClientPublishResult pubAck = await mqttClient.PublishAsync(new MqttApplicationMessageBuilder()
I would at least log it, but yeah if it wasn't successful we should either retry that one step or throw so the customer can retry.

2023-06-19 21:40 UTC, rido-min approved these changes

2023-06-19 21:42 UTC, merged