getting_started in Golang
Azure-Samples/MqttApplicationSamples pull request #74
Opened 2023-11-03 18:26 UTC by patilsnr

adds getting_started sample flow in golang using mqtt5

2023-11-03 21:02 UTC, rido-min requested changes
- This sample should be aligned with other langauges, and refactor common code to mqttclients folder to enable reuse for future samples
- Consistency with default values defined 
- Do not use autopaho
- Update READMEs
- Include instructions for mosquitto (including how to configure the CA)

2023-11-03 21:02 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +		KeepAlive:  30,
KeepAlive should be configurable

2023-11-08 22:19 UTC, rido-min requested changes
missing some envvars
move code to mosquitto clients to enable future reuse
Clarify when to use client certs vs. CaFile

Have you tested with Mosquitto ?

We also need to update all the READMEs

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	cs := MqttConnectionSettings{
we will repeat the same code in all samples. Can you move this to /mqttclients ?

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	Username  string
why username but no password?

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +		KeyFile:   os.Getenv("MQTT_KEY_FILE"),
I miss some initialization, such as UseTls, or tcpPort

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	cert, err := tls.LoadX509KeyPair(fmt.Sprintf("../%s", cs.CaFile), fmt.Sprintf("../%s", cs.KeyFile))
mmhhh LoadX509KeyPair seems needed to load the private key, not needed here. Is there any LoadPem? or similar

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	fmt.Println("Loading certificates")
we should load the CAFile only if the envvar was set

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +		Certificates: []tls.Certificate{cert},
we need to load client certificate if specified

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	fmt.Println("Dialing Eventgrid")
Dialing?

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	conn, err := tls.Dial("tcp", fmt.Sprintf("%s:%d", cs.Hostname, cs.TcpPort), cfg)
what if UseTls was set to false?

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +		CleanStart:   true,
why not configuring CleanStart ?

2023-11-08 22:19 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +		CaFile:    os.Getenv("MQTT_CERT_FILE"),
do not confuse CaFile with CertFile

2023-11-11 01:39 UTC, rido-min requested changes
This is looking great !!, 

although I think it still missing tests, and README updates (not only the Getting Started README).

Have you tested in mosquitto and EG?
Is the codespaces devContainer ready for GO?

2023-11-11 01:39 UTC, rido-min commented on scenarios/getting_started/go/getting_started.go
> +	cs := ConnectionSettings.loadConnectionSettings("../.env")
we should not hardcode the path to the .env file, or we accept as an argument, or we try to load from current dir.

2023-11-13 19:03 UTC, rido-min requested changes
any chance to unit test connectionsettings.go?
I'm missing some logic to enable/disable TLS

Have you tried with mosquitto?

2023-11-13 19:05 UTC, patilsnr commented
> any chance to unit test connectionsettings.go? I'm missing some logic to enable/disable TLS
> 
> Have you tried with mosquitto?

I'm still addressing your comments and pushing periodically. I will let you know when this is ready for a proper review.

2023-11-13 19:53 UTC, rido-min commented
> > any chance to unit test connectionsettings.go? I'm missing some logic to enable/disable TLS
> > Have you tried with mosquitto?
> 
> I'm still addressing your comments and pushing periodically. I will let you know when this is ready for a proper review.

you can set the PR as draft until it's ready

2023-11-14 16:23 UTC, rido-min commented on .gitignore
> +*.exe
this will only work on Windows, not linux (no extension)

We should find a way to exclude the output folder.

2023-11-14 17:43 UTC, patilsnr commented
/azp run

2023-11-14 18:39 UTC, rido-min approved these changes
LGTM

2023-11-14 18:43 UTC, merged